name: Pomodoro
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  flutter_icons: ^1.1.0
  animated_text_kit: ^2.2.0

  color_panel:
    path: plugins/color_panel
  file_chooser:
    path: plugins/file_chooser
  menubar:
    path: plugins/menubar
  window_size:
    path: plugins/window_size

  path_provider: ^1.6.5
  path_provider_fde:
    path: plugins/flutter_plugins/path_provider_fde
  shared_preferences: ^0.5.6
  url_launcher: ^5.5.0
  url_launcher_fde:
    path: plugins/flutter_plugins/url_launcher_fde
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true